name: Build and Deploy to itch.io

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Godot 4.2.1
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
          unzip Godot_v4.2.1-stable_linux.x86_64.zip
          chmod +x Godot_v4.2.1-stable_linux.x86_64
          
      - name: Download Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.2.1.stable
          wget https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          cd ~/.local/share/godot/export_templates/4.2.1.stable
          tar xzf ~/Godot_v4.2.1-stable_export_templates.tpz
          
      - name: Export Godot Project
        run: |
          ./Godot_v4.2.1-stable_linux.x86_64 --headless --export-release "Windows Desktop" ../DL-Builds/Windows/Dungeon\ Life.exe
          ./Godot_v4.2.1-stable_linux.x86_64 --headless --export-release "Linux" ../DL-Builds/Linux/Dungeon\ Life.zip
          
      - name: Download Butler
        run: |
          wget https://broth.itch.ovh/butler/linux-amd64/LATEST/butler -O ./butler
          chmod +x ./butler
          
      - name: Push to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          ./butler push ./builds/windows/ daremane/dungeon-life:windows
          ./butler push ./builds/linux/ daremane/dungeon-life:linux
